################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../eigen/test/adjoint.cpp \
../eigen/test/array.cpp \
../eigen/test/array_for_matrix.cpp \
../eigen/test/array_replicate.cpp \
../eigen/test/array_reverse.cpp \
../eigen/test/bandmatrix.cpp \
../eigen/test/basicstuff.cpp \
../eigen/test/bdcsvd.cpp \
../eigen/test/bicgstab.cpp \
../eigen/test/block.cpp \
../eigen/test/cholesky.cpp \
../eigen/test/cholmod_support.cpp \
../eigen/test/commainitializer.cpp \
../eigen/test/conjugate_gradient.cpp \
../eigen/test/conservative_resize.cpp \
../eigen/test/corners.cpp \
../eigen/test/ctorleak.cpp \
../eigen/test/denseLM.cpp \
../eigen/test/dense_storage.cpp \
../eigen/test/determinant.cpp \
../eigen/test/diagonal.cpp \
../eigen/test/diagonalmatrices.cpp \
../eigen/test/dontalign.cpp \
../eigen/test/dynalloc.cpp \
../eigen/test/eigen2support.cpp \
../eigen/test/eigensolver_complex.cpp \
../eigen/test/eigensolver_generalized_real.cpp \
../eigen/test/eigensolver_generic.cpp \
../eigen/test/eigensolver_selfadjoint.cpp \
../eigen/test/evaluators.cpp \
../eigen/test/exceptions.cpp \
../eigen/test/first_aligned.cpp \
../eigen/test/geo_alignedbox.cpp \
../eigen/test/geo_eulerangles.cpp \
../eigen/test/geo_homogeneous.cpp \
../eigen/test/geo_hyperplane.cpp \
../eigen/test/geo_orthomethods.cpp \
../eigen/test/geo_parametrizedline.cpp \
../eigen/test/geo_quaternion.cpp \
../eigen/test/geo_transformations.cpp \
../eigen/test/hessenberg.cpp \
../eigen/test/householder.cpp \
../eigen/test/integer_types.cpp \
../eigen/test/inverse.cpp \
../eigen/test/is_same_dense.cpp \
../eigen/test/jacobi.cpp \
../eigen/test/jacobisvd.cpp \
../eigen/test/linearstructure.cpp \
../eigen/test/lscg.cpp \
../eigen/test/lu.cpp \
../eigen/test/mapped_matrix.cpp \
../eigen/test/mapstaticmethods.cpp \
../eigen/test/mapstride.cpp \
../eigen/test/meta.cpp \
../eigen/test/metis_support.cpp \
../eigen/test/miscmatrices.cpp \
../eigen/test/mixingtypes.cpp \
../eigen/test/nesting_ops.cpp \
../eigen/test/nomalloc.cpp \
../eigen/test/nullary.cpp \
../eigen/test/packetmath.cpp \
../eigen/test/pardiso_support.cpp \
../eigen/test/pastix_support.cpp \
../eigen/test/permutationmatrices.cpp \
../eigen/test/prec_inverse_4x4.cpp \
../eigen/test/product_extra.cpp \
../eigen/test/product_large.cpp \
../eigen/test/product_mmtr.cpp \
../eigen/test/product_notemporary.cpp \
../eigen/test/product_selfadjoint.cpp \
../eigen/test/product_small.cpp \
../eigen/test/product_symm.cpp \
../eigen/test/product_syrk.cpp \
../eigen/test/product_trmm.cpp \
../eigen/test/product_trmv.cpp \
../eigen/test/product_trsolve.cpp \
../eigen/test/qr.cpp \
../eigen/test/qr_colpivoting.cpp \
../eigen/test/qr_fullpivoting.cpp \
../eigen/test/qtvector.cpp \
../eigen/test/rand.cpp \
../eigen/test/real_qz.cpp \
../eigen/test/redux.cpp \
../eigen/test/ref.cpp \
../eigen/test/resize.cpp \
../eigen/test/rvalue_types.cpp \
../eigen/test/schur_complex.cpp \
../eigen/test/schur_real.cpp \
../eigen/test/selfadjoint.cpp \
../eigen/test/simplicial_cholesky.cpp \
../eigen/test/sizeof.cpp \
../eigen/test/sizeoverflow.cpp \
../eigen/test/smallvectors.cpp \
../eigen/test/sparseLM.cpp \
../eigen/test/sparse_basic.cpp \
../eigen/test/sparse_block.cpp \
../eigen/test/sparse_permutations.cpp \
../eigen/test/sparse_product.cpp \
../eigen/test/sparse_ref.cpp \
../eigen/test/sparse_solvers.cpp \
../eigen/test/sparse_vector.cpp \
../eigen/test/sparselu.cpp \
../eigen/test/sparseqr.cpp \
../eigen/test/special_numbers.cpp \
../eigen/test/spqr_support.cpp \
../eigen/test/stable_norm.cpp \
../eigen/test/stddeque.cpp \
../eigen/test/stdlist.cpp \
../eigen/test/stdvector.cpp \
../eigen/test/stdvector_overload.cpp \
../eigen/test/superlu_support.cpp \
../eigen/test/swap.cpp \
../eigen/test/triangular.cpp \
../eigen/test/umeyama.cpp \
../eigen/test/umfpack_support.cpp \
../eigen/test/unalignedassert.cpp \
../eigen/test/unalignedcount.cpp \
../eigen/test/upperbidiagonalization.cpp \
../eigen/test/vectorization_logic.cpp \
../eigen/test/vectorwiseop.cpp \
../eigen/test/visitor.cpp \
../eigen/test/zerosized.cpp 

OBJS += \
./eigen/test/adjoint.o \
./eigen/test/array.o \
./eigen/test/array_for_matrix.o \
./eigen/test/array_replicate.o \
./eigen/test/array_reverse.o \
./eigen/test/bandmatrix.o \
./eigen/test/basicstuff.o \
./eigen/test/bdcsvd.o \
./eigen/test/bicgstab.o \
./eigen/test/block.o \
./eigen/test/cholesky.o \
./eigen/test/cholmod_support.o \
./eigen/test/commainitializer.o \
./eigen/test/conjugate_gradient.o \
./eigen/test/conservative_resize.o \
./eigen/test/corners.o \
./eigen/test/ctorleak.o \
./eigen/test/denseLM.o \
./eigen/test/dense_storage.o \
./eigen/test/determinant.o \
./eigen/test/diagonal.o \
./eigen/test/diagonalmatrices.o \
./eigen/test/dontalign.o \
./eigen/test/dynalloc.o \
./eigen/test/eigen2support.o \
./eigen/test/eigensolver_complex.o \
./eigen/test/eigensolver_generalized_real.o \
./eigen/test/eigensolver_generic.o \
./eigen/test/eigensolver_selfadjoint.o \
./eigen/test/evaluators.o \
./eigen/test/exceptions.o \
./eigen/test/first_aligned.o \
./eigen/test/geo_alignedbox.o \
./eigen/test/geo_eulerangles.o \
./eigen/test/geo_homogeneous.o \
./eigen/test/geo_hyperplane.o \
./eigen/test/geo_orthomethods.o \
./eigen/test/geo_parametrizedline.o \
./eigen/test/geo_quaternion.o \
./eigen/test/geo_transformations.o \
./eigen/test/hessenberg.o \
./eigen/test/householder.o \
./eigen/test/integer_types.o \
./eigen/test/inverse.o \
./eigen/test/is_same_dense.o \
./eigen/test/jacobi.o \
./eigen/test/jacobisvd.o \
./eigen/test/linearstructure.o \
./eigen/test/lscg.o \
./eigen/test/lu.o \
./eigen/test/mapped_matrix.o \
./eigen/test/mapstaticmethods.o \
./eigen/test/mapstride.o \
./eigen/test/meta.o \
./eigen/test/metis_support.o \
./eigen/test/miscmatrices.o \
./eigen/test/mixingtypes.o \
./eigen/test/nesting_ops.o \
./eigen/test/nomalloc.o \
./eigen/test/nullary.o \
./eigen/test/packetmath.o \
./eigen/test/pardiso_support.o \
./eigen/test/pastix_support.o \
./eigen/test/permutationmatrices.o \
./eigen/test/prec_inverse_4x4.o \
./eigen/test/product_extra.o \
./eigen/test/product_large.o \
./eigen/test/product_mmtr.o \
./eigen/test/product_notemporary.o \
./eigen/test/product_selfadjoint.o \
./eigen/test/product_small.o \
./eigen/test/product_symm.o \
./eigen/test/product_syrk.o \
./eigen/test/product_trmm.o \
./eigen/test/product_trmv.o \
./eigen/test/product_trsolve.o \
./eigen/test/qr.o \
./eigen/test/qr_colpivoting.o \
./eigen/test/qr_fullpivoting.o \
./eigen/test/qtvector.o \
./eigen/test/rand.o \
./eigen/test/real_qz.o \
./eigen/test/redux.o \
./eigen/test/ref.o \
./eigen/test/resize.o \
./eigen/test/rvalue_types.o \
./eigen/test/schur_complex.o \
./eigen/test/schur_real.o \
./eigen/test/selfadjoint.o \
./eigen/test/simplicial_cholesky.o \
./eigen/test/sizeof.o \
./eigen/test/sizeoverflow.o \
./eigen/test/smallvectors.o \
./eigen/test/sparseLM.o \
./eigen/test/sparse_basic.o \
./eigen/test/sparse_block.o \
./eigen/test/sparse_permutations.o \
./eigen/test/sparse_product.o \
./eigen/test/sparse_ref.o \
./eigen/test/sparse_solvers.o \
./eigen/test/sparse_vector.o \
./eigen/test/sparselu.o \
./eigen/test/sparseqr.o \
./eigen/test/special_numbers.o \
./eigen/test/spqr_support.o \
./eigen/test/stable_norm.o \
./eigen/test/stddeque.o \
./eigen/test/stdlist.o \
./eigen/test/stdvector.o \
./eigen/test/stdvector_overload.o \
./eigen/test/superlu_support.o \
./eigen/test/swap.o \
./eigen/test/triangular.o \
./eigen/test/umeyama.o \
./eigen/test/umfpack_support.o \
./eigen/test/unalignedassert.o \
./eigen/test/unalignedcount.o \
./eigen/test/upperbidiagonalization.o \
./eigen/test/vectorization_logic.o \
./eigen/test/vectorwiseop.o \
./eigen/test/visitor.o \
./eigen/test/zerosized.o 

CPP_DEPS += \
./eigen/test/adjoint.d \
./eigen/test/array.d \
./eigen/test/array_for_matrix.d \
./eigen/test/array_replicate.d \
./eigen/test/array_reverse.d \
./eigen/test/bandmatrix.d \
./eigen/test/basicstuff.d \
./eigen/test/bdcsvd.d \
./eigen/test/bicgstab.d \
./eigen/test/block.d \
./eigen/test/cholesky.d \
./eigen/test/cholmod_support.d \
./eigen/test/commainitializer.d \
./eigen/test/conjugate_gradient.d \
./eigen/test/conservative_resize.d \
./eigen/test/corners.d \
./eigen/test/ctorleak.d \
./eigen/test/denseLM.d \
./eigen/test/dense_storage.d \
./eigen/test/determinant.d \
./eigen/test/diagonal.d \
./eigen/test/diagonalmatrices.d \
./eigen/test/dontalign.d \
./eigen/test/dynalloc.d \
./eigen/test/eigen2support.d \
./eigen/test/eigensolver_complex.d \
./eigen/test/eigensolver_generalized_real.d \
./eigen/test/eigensolver_generic.d \
./eigen/test/eigensolver_selfadjoint.d \
./eigen/test/evaluators.d \
./eigen/test/exceptions.d \
./eigen/test/first_aligned.d \
./eigen/test/geo_alignedbox.d \
./eigen/test/geo_eulerangles.d \
./eigen/test/geo_homogeneous.d \
./eigen/test/geo_hyperplane.d \
./eigen/test/geo_orthomethods.d \
./eigen/test/geo_parametrizedline.d \
./eigen/test/geo_quaternion.d \
./eigen/test/geo_transformations.d \
./eigen/test/hessenberg.d \
./eigen/test/householder.d \
./eigen/test/integer_types.d \
./eigen/test/inverse.d \
./eigen/test/is_same_dense.d \
./eigen/test/jacobi.d \
./eigen/test/jacobisvd.d \
./eigen/test/linearstructure.d \
./eigen/test/lscg.d \
./eigen/test/lu.d \
./eigen/test/mapped_matrix.d \
./eigen/test/mapstaticmethods.d \
./eigen/test/mapstride.d \
./eigen/test/meta.d \
./eigen/test/metis_support.d \
./eigen/test/miscmatrices.d \
./eigen/test/mixingtypes.d \
./eigen/test/nesting_ops.d \
./eigen/test/nomalloc.d \
./eigen/test/nullary.d \
./eigen/test/packetmath.d \
./eigen/test/pardiso_support.d \
./eigen/test/pastix_support.d \
./eigen/test/permutationmatrices.d \
./eigen/test/prec_inverse_4x4.d \
./eigen/test/product_extra.d \
./eigen/test/product_large.d \
./eigen/test/product_mmtr.d \
./eigen/test/product_notemporary.d \
./eigen/test/product_selfadjoint.d \
./eigen/test/product_small.d \
./eigen/test/product_symm.d \
./eigen/test/product_syrk.d \
./eigen/test/product_trmm.d \
./eigen/test/product_trmv.d \
./eigen/test/product_trsolve.d \
./eigen/test/qr.d \
./eigen/test/qr_colpivoting.d \
./eigen/test/qr_fullpivoting.d \
./eigen/test/qtvector.d \
./eigen/test/rand.d \
./eigen/test/real_qz.d \
./eigen/test/redux.d \
./eigen/test/ref.d \
./eigen/test/resize.d \
./eigen/test/rvalue_types.d \
./eigen/test/schur_complex.d \
./eigen/test/schur_real.d \
./eigen/test/selfadjoint.d \
./eigen/test/simplicial_cholesky.d \
./eigen/test/sizeof.d \
./eigen/test/sizeoverflow.d \
./eigen/test/smallvectors.d \
./eigen/test/sparseLM.d \
./eigen/test/sparse_basic.d \
./eigen/test/sparse_block.d \
./eigen/test/sparse_permutations.d \
./eigen/test/sparse_product.d \
./eigen/test/sparse_ref.d \
./eigen/test/sparse_solvers.d \
./eigen/test/sparse_vector.d \
./eigen/test/sparselu.d \
./eigen/test/sparseqr.d \
./eigen/test/special_numbers.d \
./eigen/test/spqr_support.d \
./eigen/test/stable_norm.d \
./eigen/test/stddeque.d \
./eigen/test/stdlist.d \
./eigen/test/stdvector.d \
./eigen/test/stdvector_overload.d \
./eigen/test/superlu_support.d \
./eigen/test/swap.d \
./eigen/test/triangular.d \
./eigen/test/umeyama.d \
./eigen/test/umfpack_support.d \
./eigen/test/unalignedassert.d \
./eigen/test/unalignedcount.d \
./eigen/test/upperbidiagonalization.d \
./eigen/test/vectorization_logic.d \
./eigen/test/vectorwiseop.d \
./eigen/test/visitor.d \
./eigen/test/zerosized.d 


# Each subdirectory must supply rules for building sources it contributes
eigen/test/%.o: ../eigen/test/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


